"""fixed user deletion bug and indexed some columns

Revision ID: 021ba0c322dd
Revises: 4662ccd2ddf6
Create Date: 2026-03-20 19:41:00.170091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021ba0c322dd'
down_revision: Union[str, Sequence[str], None] = '4662ccd2ddf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_date_created'), 'comments', ['date_created'], unique=False)
    op.create_index(op.f('ix_posts_date_created'), 'posts', ['date_created'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_date_expire'), 'refresh_tokens', ['date_expire'], unique=False)
    op.add_column('user_deletions', sa.Column('deleted_by', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('user_deletions_username_key'), 'user_deletions', type_='unique')
    op.create_index(op.f('ix_user_deletions_deleted_at'), 'user_deletions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_deletions_user_id'), 'user_deletions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_deletions_username'), 'user_deletions', ['username'], unique=True)
    op.drop_constraint(op.f('user_deletions_username_fkey'), 'user_deletions', type_='foreignkey')
    op.create_foreign_key(None, 'user_deletions', 'users', ['deleted_by'], ['id'])
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_constraint(None, 'user_deletions', type_='foreignkey')
    op.create_foreign_key(op.f('user_deletions_username_fkey'), 'user_deletions', 'users', ['username'], ['username'])
    op.drop_index(op.f('ix_user_deletions_username'), table_name='user_deletions')
    op.drop_index(op.f('ix_user_deletions_user_id'), table_name='user_deletions')
    op.drop_index(op.f('ix_user_deletions_deleted_at'), table_name='user_deletions')
    op.create_unique_constraint(op.f('user_deletions_username_key'), 'user_deletions', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_deletions', 'deleted_by')
    op.drop_index(op.f('ix_refresh_tokens_date_expire'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_posts_date_created'), table_name='posts')
    op.drop_index(op.f('ix_comments_date_created'), table_name='comments')
    # ### end Alembic commands ###
