"""added uuid default to account recovery table

Revision ID: 31d77fff3955
Revises: 021ba0c322dd
Create Date: 2026-03-22 23:33:18.146105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31d77fff3955'
down_revision: Union[str, Sequence[str], None] = '021ba0c322dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_recovery_token_token_hash'), table_name='account_recovery_token')
    op.drop_table('account_recovery_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_recovery_token',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('account_recovery_token_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('account_recovery_token_pkey'))
    )
    op.create_index(op.f('ix_account_recovery_token_token_hash'), 'account_recovery_token', ['token_hash'], unique=False)
    # ### end Alembic commands ###
