"""added role column to user model

Revision ID: 3abd865a7987
Revises: d383069afd8e
Create Date: 2026-03-18 13:22:48.075976

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3abd865a7987"
down_revision: Union[str, Sequence[str], None] = "d383069afd8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


role_enum = sa.Enum("user", "admin", name="role")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="role"),
            server_default=sa.text("'user'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
