"""added username column in UserDeletion table

Revision ID: 4662ccd2ddf6
Revises: 75109cb372dd
Create Date: 2026-03-20 13:13:27.271188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4662ccd2ddf6"
down_revision: Union[str, Sequence[str], None] = "75109cb372dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_deletions",
        sa.Column("username", sa.String(length=200), unique=True, nullable=False),
    )
    op.create_foreign_key(None, "user_deletions", "users", ["username"], ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("username", "user_deletions", type_="foreignkey")
    op.drop_column("user_deletions", "username")
    # ### end Alembic commands ###


# RUN THIS LATER ALSO SET A VALUE FOR EXISTING DELETED RECORDS TO MAKE THIS WORK
